manifest:
  remotes:
    - name: alxcrt
      url-base: https://github.com/alxcrt/zmk
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
